export const cardsData = [
    {
        id: 1,
        title: "Task1",
        datetime: "24/1/2022 16:40 hs",
        creator: "Julio Avantt",
        description: "Desc1",
        type: "new",
        priority: "high",
    },
    {
        id: 2,
        title: "Task2",
        datetime: "24/1/2022 16:40 hs",
        creator: "Julio Avantt",
        description: "Desc1",
        type: "new",
        priority: "high",
    },
    {
        id: 3,
        title: "Task3",
        datetime: "24/1/2022 16:40 hs",
        creator: "Julio Avantt",
        description: "Desc1",
        type: "new",
        priority: "high",
    },
    {
        id: 4,
        title: "Task4",
        datetime: "24/1/2022 16:40 hs",
        creator: "Julio Avantt",
        description: "Desc1",
        type: "new",
        priority: "high",
    },
    {
        id: 5,
        title: "Task5",
        datetime: "24/1/2022 16:40 hs",
        creator: "Julio Avantt",
        description: "Desc1",
        type: "new",
        priority: "high",
    },
    {
        id: 6,
        title: "Task6",
        datetime: "24/1/2022 16:40 hs",
        creator: "Julio Avantt",
        description: "Desc1",
        type: "new",
        priority: "high",
    },
]